# Generated by Django 3.1.1 on 2021-04-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shape',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('point', models.CharField(max_length=1000)),
            ],
        ),
    ]
