# Generated by Django 3.1.1 on 2021-05-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_coord'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='shapetype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
