# Generated by Django 3.1.1 on 2021-05-11 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0004_shape_shapetype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coord',
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.AddField(
            model_name='shape',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
